### ISSUE TITLE
Are recuring payments working in test environment?

### ISSUE THREAD

**Issue by ioditis** [klix-app/klix-developer-documentation-website#5]
According documentation, registration payment was done with  "force_recurring": true,". Response contains:
```
{
  ...
  "force_recurring": true,
   ...
  "id": "80903bf9-2743-4b95-9f8a-26c1308af5a9"
}
```

New recurring payment is created and its ID is returned b61cf600-eb11-4c68-9e1e-21bef257df0e  

We try to execute recurrng payment:
https://portal.klix.app/api/v1/purchases/b61cf600-eb11-4c68-9e1e-21bef257df0e/charge
```
{
"recurring_token": "80903bf9-2743-4b95-9f8a-26c1308af5a9"
}
```

We receive response 404 - page not found.

**Comment by EdgarsM** [comment]
Be aware that all Klix API end-points end with / so in this case request should be sent to https://portal.klix.app/api/v1/purchases/b61cf600-eb11-4c68-9e1e-21bef257df0e/charge/

**Comment by ioditis** [comment]
Thanks for the quick response! It helped!
